
package cn.org.bjca.example.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceExampleServiceService", targetNamespace = "http://webservice.example.bjca.org.cn/", wsdlLocation = "http://127.0.0.1:8080/hello?wsdl")
public class WebServiceExampleServiceService
    extends Service
{

    private final static URL WEBSERVICEEXAMPLESERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEEXAMPLESERVICESERVICE_EXCEPTION;
    private final static QName WEBSERVICEEXAMPLESERVICESERVICE_QNAME = new QName("http://webservice.example.bjca.org.cn/", "WebServiceExampleServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8080/hello?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEEXAMPLESERVICESERVICE_WSDL_LOCATION = url;
        WEBSERVICEEXAMPLESERVICESERVICE_EXCEPTION = e;
    }

    public WebServiceExampleServiceService() {
        super(__getWsdlLocation(), WEBSERVICEEXAMPLESERVICESERVICE_QNAME);
    }

    public WebServiceExampleServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEEXAMPLESERVICESERVICE_QNAME, features);
    }

    public WebServiceExampleServiceService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEEXAMPLESERVICESERVICE_QNAME);
    }

    public WebServiceExampleServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEEXAMPLESERVICESERVICE_QNAME, features);
    }

    public WebServiceExampleServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceExampleServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceExampleService
     */
    @WebEndpoint(name = "WebServiceExampleServicePort")
    public WebServiceExampleService getWebServiceExampleServicePort() {
        return super.getPort(new QName("http://webservice.example.bjca.org.cn/", "WebServiceExampleServicePort"), WebServiceExampleService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceExampleService
     */
    @WebEndpoint(name = "WebServiceExampleServicePort")
    public WebServiceExampleService getWebServiceExampleServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.example.bjca.org.cn/", "WebServiceExampleServicePort"), WebServiceExampleService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEEXAMPLESERVICESERVICE_EXCEPTION!= null) {
            throw WEBSERVICEEXAMPLESERVICESERVICE_EXCEPTION;
        }
        return WEBSERVICEEXAMPLESERVICESERVICE_WSDL_LOCATION;
    }

}
