
package cn.org.bjca.example.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceExampleService", targetNamespace = "http://webservice.example.bjca.org.cn/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceExampleService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.example.bjca.org.cn/", className = "cn.org.bjca.example.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.example.bjca.org.cn/", className = "cn.org.bjca.example.client.HelloResponse")
    @Action(input = "http://webservice.example.bjca.org.cn/WebServiceExampleService/helloRequest", output = "http://webservice.example.bjca.org.cn/WebServiceExampleService/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
